# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'win1803'

trigger:
- master

steps:
- task: CmdLine@2
  inputs:
    script: 'msbuild GTS.Plugin.DemoPlugin.sln'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'artifactName'
    targetPath: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
