# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- powershell: msbuild GTS.Plugin.DemoPlugin.sln

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'artifactName'
    targetPath: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
